#!/usr/bin/env ruby

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

VALUE_LIMIT = 4_000_000

def fibonacci(prev, current, acc = [])
  return acc if current >= VALUE_LIMIT

  acc.push(current)

  fibonacci(current, current + prev, acc)
end

fibonacci(1, 2).filter(&:even?).sum
